// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: nginxlog.capnp

package org.capnproto.examples.nginxlog;

public final class NginxlogCapnp {
  public static class NginxLogLine {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)8);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return NginxLogLine.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
            new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasHost() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getHost() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setHost(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setHost(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initHost(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final boolean hasClientIP() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.Text.Builder getClientIP() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }
      public final void setClientIP(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 1, value);
      }
      public final void setClientIP(String value) {
        _setPointerField(org.capnproto.Text.factory, 1, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initClientIP(int size) {
        return _initPointerField(org.capnproto.Text.factory, 1, size);
      }
      public final boolean hasTimestamp() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.Text.Builder getTimestamp() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }
      public final void setTimestamp(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 2, value);
      }
      public final void setTimestamp(String value) {
        _setPointerField(org.capnproto.Text.factory, 2, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initTimestamp(int size) {
        return _initPointerField(org.capnproto.Text.factory, 2, size);
      }
      public final boolean hasMethod() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.Text.Builder getMethod() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }
      public final void setMethod(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 3, value);
      }
      public final void setMethod(String value) {
        _setPointerField(org.capnproto.Text.factory, 3, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initMethod(int size) {
        return _initPointerField(org.capnproto.Text.factory, 3, size);
      }
      public final boolean hasUrl() {
        return !_pointerFieldIsNull(4);
      }
      public final org.capnproto.Text.Builder getUrl() {
        return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
      }
      public final void setUrl(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 4, value);
      }
      public final void setUrl(String value) {
        _setPointerField(org.capnproto.Text.factory, 4, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initUrl(int size) {
        return _initPointerField(org.capnproto.Text.factory, 4, size);
      }
      public final boolean hasProto() {
        return !_pointerFieldIsNull(5);
      }
      public final org.capnproto.Text.Builder getProto() {
        return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
      }
      public final void setProto(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 5, value);
      }
      public final void setProto(String value) {
        _setPointerField(org.capnproto.Text.factory, 5, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initProto(int size) {
        return _initPointerField(org.capnproto.Text.factory, 5, size);
      }
      public final short getHttpStatus() {
        return _getShortField(0);
      }
      public final void setHttpStatus(short value) {
        _setShortField(0, value);
      }

      public final int getResponseLen() {
        return _getIntField(1);
      }
      public final void setResponseLen(int value) {
        _setIntField(1, value);
      }

      public final boolean hasReferer() {
        return !_pointerFieldIsNull(6);
      }
      public final org.capnproto.Text.Builder getReferer() {
        return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
      }
      public final void setReferer(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 6, value);
      }
      public final void setReferer(String value) {
        _setPointerField(org.capnproto.Text.factory, 6, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initReferer(int size) {
        return _initPointerField(org.capnproto.Text.factory, 6, size);
      }
      public final boolean hasAgent() {
        return !_pointerFieldIsNull(7);
      }
      public final org.capnproto.Text.Builder getAgent() {
        return _getPointerField(org.capnproto.Text.factory, 7, null, 0, 0);
      }
      public final void setAgent(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 7, value);
      }
      public final void setAgent(String value) {
        _setPointerField(org.capnproto.Text.factory, 7, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initAgent(int size) {
        return _initPointerField(org.capnproto.Text.factory, 7, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasHost() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getHost() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public boolean hasClientIP() {
        return !_pointerFieldIsNull(1);
      }
      public org.capnproto.Text.Reader getClientIP() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }

      public boolean hasTimestamp() {
        return !_pointerFieldIsNull(2);
      }
      public org.capnproto.Text.Reader getTimestamp() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }

      public boolean hasMethod() {
        return !_pointerFieldIsNull(3);
      }
      public org.capnproto.Text.Reader getMethod() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }

      public boolean hasUrl() {
        return !_pointerFieldIsNull(4);
      }
      public org.capnproto.Text.Reader getUrl() {
        return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
      }

      public boolean hasProto() {
        return !_pointerFieldIsNull(5);
      }
      public org.capnproto.Text.Reader getProto() {
        return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
      }

      public final short getHttpStatus() {
        return _getShortField(0);
      }

      public final int getResponseLen() {
        return _getIntField(1);
      }

      public boolean hasReferer() {
        return !_pointerFieldIsNull(6);
      }
      public org.capnproto.Text.Reader getReferer() {
        return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
      }

      public boolean hasAgent() {
        return !_pointerFieldIsNull(7);
      }
      public org.capnproto.Text.Reader getAgent() {
        return _getPointerField(org.capnproto.Text.factory, 7, null, 0, 0);
      }

    }

  }


  public static class NginxLog {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return NginxLog.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
            new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasLines() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.StructList.Builder<NginxlogCapnp.NginxLogLine.Builder> getLines() {
        return _getPointerField(NginxlogCapnp.NginxLogLine.listFactory, 0, null, 0);
      }
      public final void setLines(org.capnproto.StructList.Reader<NginxlogCapnp.NginxLogLine.Reader> value) {
        _setPointerField(NginxlogCapnp.NginxLogLine.listFactory, 0, value);
      }
      public final org.capnproto.StructList.Builder<NginxlogCapnp.NginxLogLine.Builder> initLines(int size) {
        return _initPointerField(NginxlogCapnp.NginxLogLine.listFactory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final boolean hasLines() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.StructList.Reader<NginxlogCapnp.NginxLogLine.Reader> getLines() {
        return _getPointerField(NginxlogCapnp.NginxLogLine.listFactory, 0, null, 0);
      }

    }

  }



  public static final class Schemas {
    public static final org.capnproto.SegmentReader b_baef3b31c8f59806 =
            org.capnproto.GeneratedClassSupport.decodeRawBytes(
                    "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
                            "\u0006\u0098\u00f5\u00c8\u0031\u003b\u00ef\u00ba" +
                            "\u000f\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
                            "\u0071\u00e1\u006e\u00f8\u0019\u002e\u00b3\u009e" +
                            "\u0008\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0015\u0000\u0000\u0000\u00e2\u0000\u0000\u0000" +
                            "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u001d\u0000\u0000\u0000\u0037\u0002\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u006e\u0067\u0069\u006e\u0078\u006c\u006f\u0067" +
                            "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u004e" +
                            "\u0067\u0069\u006e\u0078\u004c\u006f\u0067\u004c" +
                            "\u0069\u006e\u0065\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
                            "\u0028\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0009\u0001\u0000\u0000\u002a\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0004\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0010\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\r\u0001\u0000\u0000\u004a\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0018\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0015\u0001\u0000\u0000\u0052\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0014\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0020\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0003\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u001d\u0001\u0000\u0000\u003a\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0018\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0024\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0004\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0021\u0001\u0000\u0000\"\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u001c\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0028\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0005\u0000\u0000\u0000\u0005\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0025\u0001\u0000\u0000\u0032\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0020\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u002c\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0029\u0001\u0000\u0000\u005a\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0028\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0034\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0007\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0007\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0031\u0001\u0000\u0000\u0062\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0030\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u003c\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0008\u0000\u0000\u0000\u0006\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0008\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0039\u0001\u0000\u0000\u0042\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0034\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0040\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0009\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0009\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u003d\u0001\u0000\u0000\u0032\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0038\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0044\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u0068\u006f\u0073\u0074\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0063\u006c\u0069\u0065\u006e\u0074\u0049\u0050" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0074\u0069\u006d\u0065\u0073\u0074\u0061\u006d" +
                            "\u0070\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u006d\u0065\u0074\u0068\u006f\u0064\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0075\u0072\u006c\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0070\u0072\u006f\u0074\u006f\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0068\u0074\u0074\u0070\u0053\u0074\u0061\u0074" +
                            "\u0075\u0073\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0072\u0065\u0073\u0070\u006f\u006e\u0073\u0065" +
                            "\u004c\u0065\u006e\u0000\u0000\u0000\u0000\u0000" +
                            "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0072\u0065\u0066\u0065\u0072\u0065\u0072\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0061\u0067\u0065\u006e\u0074\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
    public static final org.capnproto.SegmentReader b_83bfed01c52e6a67 =
            org.capnproto.GeneratedClassSupport.decodeRawBytes(
                    "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
                            "\u0067\u006a\u002e\u00c5\u0001\u00ed\u00bf\u0083" +
                            "\u000f\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
                            "\u0071\u00e1\u006e\u00f8\u0019\u002e\u00b3\u009e" +
                            "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0015\u0000\u0000\u0000\u00c2\u0000\u0000\u0000" +
                            "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0019\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u006e\u0067\u0069\u006e\u0078\u006c\u006f\u0067" +
                            "\u002e\u0063\u0061\u0070\u006e\u0070\u003a\u004e" +
                            "\u0067\u0069\u006e\u0078\u004c\u006f\u0067\u0000" +
                            "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
                            "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\r\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0008\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0024\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
                            "\u006c\u0069\u006e\u0065\u0073\u0000\u0000\u0000" +
                            "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
                            "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0006\u0098\u00f5\u00c8\u0031\u003b\u00ef\u00ba" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
                            "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
  }
}

